import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {ThemeProvider} from "next-themes";
import "./globals.css";
import Footer from "@/components/Footer";
import { Navbar } from "@/components/navbar";
import Link from "next/link";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
      >
        <ThemeProvider defaultTheme="system" attribute="class" enableSystem>
          <h1
            className="fixed top-6 left-6 z-50 text-xl font-semibold tracking-tight font-[family-name:var(--font-inter)] hover:opacity-80 transition-opacity"
          >
            Rehan
          </h1>
          <Navbar/>
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
